name: Publish Jupyter Book

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter-book

      - name: Configure git authentication
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "turulomio@yahoo.es"
          git config --global user.name "turulomio"
          # This line is crucial for your issue
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n x-access-token:${GITHUB_TOKEN} | base64)"


      - name: Build Jupyter Book
        run: |
          jupyter-book build jupyter/
      - name: Upload artifact to pass to GitHub Pages
        if: success() || failure()
        uses: actions/upload-pages-artifact@v3
        with:
          path: jupyter/_build/html

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    if: success() || failure()
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
        pages: write      # to deploy to Pages
        id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
