name: Publish Jupyter Book

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  build-and-publish-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter-book ghp-import

      - name: Build Jupyter Book
        run: |
          jupyter-book build jupyter/

      - name: Publish to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "turulomio@yahoo.es"
          git config --global user.name "turulomio"
          git config --global credential.helper store
          # This next command assumes your build output is in the 'jupyter/_build/html' directory.
          ghp-import -n -p -f jupyter/_build/html
