name: Publish Jupyter Book
on:
  push:
    branches:
      - main  # Set this to your default branch.
      - 103-update-for-security-reasons


jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
        pages: write      # to deploy to Pages
        id-token: write   # to verify the deployment originates from an appropriate source
        contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter-book ghp-import pydicts
      - name: Configure git authentication
        run: |
          git config --global user.email "turulomio@yahoo.es" #gh-pages branch
          git config --global user.name "turulomio" 
      - name: Build Jupyter Book
        run: |
          cd jupyter
          BASE_URL=/pydicts jupyter book build --html --execute
      - name: Upload artifact to pass to GitHub Pages
        run: |
          cd jupyter
          ghp-import -n -p -f _build/html